memcached:
  extends:
    file: common.yml
    service: memcached
  mem_limit: 128m
mysql:
  extends:
    file: common.yml
    service: mysql
  mem_limit: 128m
  volumes_from:
    - wordpress_mysqldata
  environment:
    - MYSQL_ROOT_PASSWORD=mQ5gcrxcDcJVaDzYA6Nc
    - MYSQL_PASSWORD=Sv3Qva2w6FFVJJA95Zsr
php:
  extends:
    file: common.yml
    service: php
  mem_limit: 128m
  links:
    - memcached
    - mysql
  environment:
    - WP_DB_PASSWORD=Sv3Qva2w6FFVJJA95Zsr
  volumes_from:
    - wordpress_uploads
nginx:
  extends:
    file: common.yml
    service: nginx
  mem_limit: 128m
  links:
    - php
  volumes_from:
    - wordpress_uploads
