memcached:
  extends:
    file: common.yml
    service: memcached
mysqldata:
  extends:
    file: common.yml
    service: mysqldata
mysql:
  extends:
    file: common.yml
    service: mysql
  volumes_from:
    - mysqldata
  environment:
    - MYSQL_ROOT_PASSWORD=mQ5gcrxcDcJVaDzYA6Nc
    - MYSQL_PASSWORD=Sv3Qva2w6FFVJJA95Zsr
uploads:
  extends:
    file: common.yml
    service: uploads
  volumes:
    - /srv/www/wordpress/content/uploads
php:
  extends:
    file: common.yml
    service: php
  links:
    - memcached
    - mysql
  environment:
    - WP_DB_PASSWORD=Sv3Qva2w6FFVJJA95Zsr
  volumes_from:
    - uploads
nginx:
  extends:
    file: common.yml
    service: nginx
  links:
    - php
  volumes_from:
    - uploads
  ports:
    - "80:80"
